import { useEffect, useRef } from 'react'
import { Link } from 'react-router-dom'
import gsap from 'gsap'
import { ArrowDown, ArrowUpRight, Award, Globe, Megaphone, MapPin, Map } from 'lucide-react'
import { SEO, ButtonLink, SectionTitle, Accordion, ContactCTA, Gallery } from '../components/Site'
import { services, process, topics, faqs, contact } from '../data/siteData'

export default function Home() {
  const hero = useRef(); const impact = useRef()
  useEffect(() => { if (matchMedia('(prefers-reduced-motion: reduce)').matches) return; const ctx = gsap.context(() => { gsap.timeline().from('.hero__word', { y: '110%', stagger: .075, duration: .85, ease: 'power4.out' }).from('.hero__intro > *', { y: 24, opacity: 0, stagger: .1, duration: .55 }, '-=.3'); gsap.to('.hero__bg', { scale: 1.08, duration: 10, ease: 'none' }); gsap.from('.impact__second', { scale: .72, opacity: .2, scrollTrigger: { trigger: impact.current, start: 'top 75%', end: 'bottom 50%', scrub: 1 } }) }, hero); return () => ctx.revert() }, [])
  const schema = [{ '@context': 'https://schema.org', '@type': 'Organization', name: contact.name, url: 'https://www.nukkadnatak.in', telephone: contact.phone, email: contact.email, address: { '@type': 'PostalAddress', streetAddress: 'First Floor, Aashirwad Complex, Pitampura', addressLocality: 'New Delhi', postalCode: '110034', addressCountry: 'IN' } }]
  return <><SEO schema={schema} />
    <section className="hero" ref={hero}><img className="hero__bg" src="/images/new.png" width="1680" height="940" fetchPriority="high" alt="Nukkad Natak performers engaging a public audience in Delhi" /><div className="hero__shade" /><div className="hero__content"><span className="eyebrow">VOICE · STORY · CHANGE</span><h1 aria-label="nukkadnatak.in The Nukkad Natak Group">{['nukkadnatak.in', 'The Nukkad Natak Group'].map((x, i) => <span className={i === 1 ? 'accent' : ''} key={x}><i className="hero__word">{x}</i></span>)}</h1><div className="hero__intro"><p>We create professionally crafted Nukkad Natak and street play campaigns that educate, engage and move audiences. From public awareness and social campaigns to corporate and government initiatives, we transform important messages into powerful experiences that connect with audiences across India.</p><div className="button-row"><ButtonLink light>Get a Quote</ButtonLink><ButtonLink to="/our-work">Explore Our Work</ButtonLink></div><small>From script development to nationwide on-ground execution.</small></div></div><a href="#impact" className="hero__scroll">SCROLL TO ENTER <ArrowDown /></a></section>

    <section id="impact" className="impact" ref={impact}><p>AWARENESS SHOULD NEVER FEEL LIKE AN AD</p><h2 className="impact__second">MAKE PEOPLE STOP.<br /><em>LISTEN. REMEMBER.</em></h2></section>

    <section className="intro section"><SectionTitle eyebrow="THE MOST DIRECT STAGE" title="THE STREET IS WHERE THE MESSAGE MEETS PEOPLE." /><div className="intro__grid"><div className="intro__image"><img loading="lazy" src="/images/street-theatre-rehearsal-delhi.webp" width="1536" height="1024" alt="Delhi street theatre ensemble rehearsing together" /></div><div className="intro__copy"><p className="lead">Nukkad Natak brings a message out of the script and into the lives of the people it is meant to reach.</p><p>There is no screen between the performer and the audience. Just a story, a shared moment and a message that feels personal. From research and scripting to performance and execution, every campaign is created to make people pause, connect and take something meaningful with them.</p><ButtonLink to="/about">Discover Our Story</ButtonLink><blockquote>“The audience is not outside the story. They are part of it.”</blockquote></div></div></section>



    <section className="why section"><SectionTitle eyebrow="WHY NUKKAD NATAK" title="Why Street Theatre Creates Real Engagement" /><div className="stage"><div className="stage__center"><span>LIVE</span><strong>Human<br />Connection</strong></div>{['CROWDS GATHER', 'MESSAGES LAND', 'PEOPLE PARTICIPATE', 'STORIES STAY', 'CONVERSATIONS BEGIN'].map((x, i) => <div className={`stage__point p${i + 1}`} key={x}><span>0{i + 1}</span><div className="point-text">{x}</div></div>)}</div></section>

    <section className="journey section section--parchment"><SectionTitle eyebrow="CAMPAIGN JOURNEY" title="From Message to Movement" /><div className="timeline">{process.map((x, i) => <div className="timeline__step" key={x}><span>{String(i + 1).padStart(2, '0')}</span><h3>{x}</h3><p>{i === 0 ? 'We define the objective, audience and context.' : i === 1 ? 'Research becomes a clear, relevant performance script.' : i === 2 ? 'The right ensemble finds the rhythm, voice and movement.' : i === 3 ? 'Locations, logistics and approvals become one operating plan.' : i === 4 ? 'Performances meet audiences in real public spaces.' : 'Campaign activity is documented for review and learning.'}</p></div>)}</div></section>

    <section className="topics-preview section"><SectionTitle eyebrow="THE SCALE OF THE WORK" title="MORE THAN A PERFORMANCE. A REACH." copy="From local communities to nationwide campaigns, every number represents people reached, messages delivered and stories brought to life." /><div className="topic-wall">{(() => { const stats = [{ icon: Award, title: '10+', text: 'YEARS Experience' },{ icon: Globe, title: '13+', text: 'LANGUAGES' },{ icon: Megaphone, title: '200+', text: 'CAMPAIGNS' },{ icon: MapPin, title: '100+', text: 'LOCATIONS' },{ icon: Map, title: 'PAN INDIA', text: 'REACH' }]; return stats.map((s, i) => { const Icon = s.icon; return <div key={i} className={`topic-block topic-block--${i}`}><span style={{display: 'flex', alignItems: 'center', gap: '0.75rem', opacity: 0.8, fontSize: '1.25rem', fontWeight: 500, marginBottom: '1rem'}}><Icon size={32} strokeWidth={1.5} /> 0{i + 1}</span><h3 style={{fontSize: 'clamp(2.5rem, 5vw, 4rem)', marginBottom: '0.5rem'}}>{s.title}</h3><p style={{fontSize: '1.2rem', letterSpacing: '0.1em'}}>{s.text}</p></div> }) })()}</div></section>



    <section className="clients-section">{(()=>{const CLD='https://res.cloudinary.com/crw5jo8x/image/upload/h_200/';const logos=[['new_railways_qexq8i','Indian Railways'],['Bharat_sv7ccc','Bharat Petroleum'],['tret_xfn8ki','PCRA'],['nsdc_uh93t3','NSDC'],['Dairy_mjqxm1','Mother Dairy'],['Tang_vftt0d','Tang'],['Gail_gqromt','GAIL'],['TCI_q6hpjb','TCI'],['tata_swatch_b4ohqh','Tata Swach'],['Tata_power_pswa75','Tata Power'],['SOny_euf8c8','Sony'],['pnb_bank_pgqymi','PNB Bank'],['Silica_2_svgzte','Silica'],['Nicklodeon_sz5s1k','Nickelodeon'],['Oil_India_fok39z','Oil India'],['National_Health_Mission_kbgmsa','National Health Mission'],['NBCC_w00egi','NBCC'],['indian_railways_sfu8rk','Indian Railways'],['Mountain_Dew_jhnyw3','Mountain Dew'],['MCI_Delhi_wmbozk','MCI Delhi'],['Jal_Shakti_mwemya','Jal Shakti'],['Hp_petrol_khfnxj','HP Petroleum'],['Indian_oil_qefnsy','Indian Oil'],['Dove_k2zqm4','Dove'],['India_post_sgloau','India Post'],['Honda_wpxvqg','Honda'],['ghaziabad_q1hiqf','Ghaziabad'],['Dell_fdltie','Dell'],['Delhi_police_osvnjr','Delhi Police'],['Colgate_isjtym','Colgate'],['Bureau_ru4g8c','Bureau'],['Celebrity_uxy4xs','Celebrity Fitness'],['Cadbury_zv1qgp','Cadbury'],['BSES_wpmnsy','BSES'],['Apollo_vpjtby','Apollo Hospitals']];const row1=logos.slice(0,18);const row2=logos.slice(18);return <><p className="eyebrow">OUR CLIENTS</p><h2>Trusted by India's leading <em>brands</em> and <em>government bodies</em></h2><div className="marquee-wrap"><div className="marquee-track">{[...row1,...row1].map(([id,name],i)=><img key={i} className="marquee-logo" src={`${CLD}${id}`} alt={name} loading="lazy" height="200"/>)}</div></div><div className="marquee-wrap"><div className="marquee-track marquee-track--reverse">{[...row2,...row2].map(([id,name],i)=><img key={i} className="marquee-logo" src={`${CLD}${id}`} alt={name} loading="lazy" height="200"/>)}</div></div></>})()}</section>

    <ContactCTA />
  </>
}
